articles/urls.py
from articles import views
from django.urls import path

app_name = 'articles'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('articles/<str:headline>', views.ArticleView.as_view(), name='article'),
    path('comments', views.CommentView.as_view())
]

fool/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models


class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    comment_text = models.TextField()
    article_uuid = models.UUIDField()

articles/views.py
import json
import random
from articles.api import get_articles, get_quotes
from articles.models import Comment
from dateutil.parser import parse
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView, View


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        articles = get_articles()['results']
        # get first article from api with tag slug=10-promise to display as main article
        main_article = next(iter([a for a in articles if '10-promise' in [t['slug'] for t in a['tags']]]), None)
        if main_article:
            url_headline = strip_headline_for_url(main_article['headline'])
            image_url = self.get_featured_image_url(main_article)

            context['main_article'] = { 'headline': main_article['headline'],
                                        'url_headline': url_headline,
                                        'image_url': image_url,
                                        'author': main_article['byline'],
                                        'publish_date': parse(main_article['publish_at']).strftime('%B %-d, %Y'),
                                        'promo': main_article['promo']
                                        }
            articles.remove(main_article)
        else:
            context['main_article'] = {}

        # from the remaining articles take 3 at random to display below the main article
        other_articles = random.sample(articles, 3)
        context['other_articles'] = []
        for article in other_articles:
          url_headline = strip_headline_for_url(article['headline'])
          image_url = self.get_featured_image_url(article)
          context['other_articles'].append({
                                    'headline': article['headline'],
                                    'url_headline': url_headline,
                                    'image_url': image_url,
                                    'author': article['byline'],
                                    'publish_date': parse(article['publish_at']).strftime('%B %-d, %Y'),
                                    'promo': article['promo']
          })

        return context

    def get_featured_image_url(self, article):
        return next(iter([i['url'] for i in article['images'] if i['featured'] == True]), None)


class ArticleView(TemplateView):
    template_name = 'article.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = get_articles()['results']

        # get the article matching the headline from the url with related comments
        article = next(iter([a for a in articles if strip_headline_for_url(a['headline']) == kwargs['headline']]))
        if article:
            comments = [c.comment_text for c in Comment.objects.filter(article_uuid=article['uuid'])]
            context['article'] = {'headline': article['headline'],
                                    'author': article['byline'],
                                    'publish_datetime': parse(article['publish_at']).strftime('%B %-d, %Y at %-I:%M%p'),
                                    'body': article['body'].replace('{%sfr%}',''),
                                    'disclosure': article['disclosure'],
                                    'uuid': article['uuid'],
                                    'comments': comments
                                    }

            articles.remove(article)
        else:
            context['article'] = {}

        latest_headlines = []
        # from the remaining articles take the 5 most recently published to display as latest headlines
        for a in list(reversed(sorted(articles, key=lambda x: x['publish_at'])))[:5]:
            latest_headlines.append({'headline': a['headline'], 'url_headline': strip_headline_for_url(a['headline'])})
        context['latest_headlines'] = latest_headlines

        # get quotes related to the article from the api data
        instrument_ids = [i['instrument_id'] for i in article['instruments']]
        quotes = []
        for q in get_quotes():
            # there are duplicates in the quote data, for example INTC, so an extra de-duplication check is needed
            if q['InstrumentId'] in instrument_ids and q not in quotes:
                quotes.append(q)

        for q in quotes:
            q['change_percent'] = round(q['PercentChange']['Value'] * 100, 2)

        context['quotes'] = quotes
        return context


@method_decorator(csrf_exempt, name='dispatch')
class CommentView(View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        payload = json.loads(request.body)
        Comment.objects.create(comment_text=payload['comment'], article_uuid=payload['article_uuid'])
        response = HttpResponse(status=201)
        return response
    

def strip_headline_for_url(headline):
    # return headline in lowercase, with non-alphanumeric characters removed, and spaces replaced with dashes
    return ''.join([i for i in headline if i.isalnum() or i == ' ']).replace(' ','-').lower()

articles/templates/article.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% include "navigation.html" %}

<div class="container article-content-inner">
    <div class="row">
        <div class="col-sm-12">
            <div class="article-header">
                <header>
                    <div id="adv_text" class="adv-heading"></div>
                    <h1>{{ article.headline }}</h1>
                </header>
            </div>
        </div>
    </div>
    <div class="row">
        <main class="col-sm-7 col-md-8">
            <div class="author-tagline author-inline">
                <div class="author-and-date">
                    <div class="author-byline">
                        <div class="author-name">{{ article.author }}</div>
                    </div>
                    <div class="article-pub-date">
                        <div class="publication-date">
                            {{ article.publish_datetime }}
                        </div>
                    </div>
                </div>
            </div>
            <section class="article-body">
                <div class="article-content">
                    {% autoescape off %}
                    {{ article.body }}
                    {% endautoescape %}
                </div>
                <div class="article-disclosure">
                    {% autoescape off %}
                    {{ article.disclosure }}
                    {% endautoescape %}
                </div>
            </section>
            <section class="article-comments">
                    <div class="block-title">
                        <hr><h2>Comments</h2>
                    </div>
                    <ul id="comment-list" class="two-line-list">
                        {% if not article.comments %}
                            <li>No comments yet!</li>
                        {% else %}
                            {% for comment in article.comments %}
                                <li>{{ comment }}</li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                    <label for="comment-input">Add a comment:</label>
                    <textarea id="comment-input" rows="2"></textarea>
                    <button id="comment-btn" type="button" onclick="addComment('{{ article.uuid }}');">Post comment</button>
            </section>
        </main>
        <aside class="col-sm-5 col-md-4 p-l">
            <section class="related-tickers">
                {% include "quotes.html" with quotes=quotes %}
            </section>
            <section class="read-more-section">
                {% include "headlines.html" with headlines=latest_headlines %}
            </section>
        </aside>
    </div>
</div>
{% endblock %}

articles/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>html</title>

        <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
        <link rel="icon" type="image/png" href="img/facvicon.png">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        {% block content %}{% endblock %}
        <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

articles/templates/headlines.html
<div class="block-title">
        <hr><h2>Read More</h2>
</div>
<ul class="two-line-list">
    {% for headline in headlines %}
        <li><a href="{% url 'articles:article' headline.url_headline %}">{{ headline.headline }}</a></li>
    {% endfor %}
</ul>

articles/templates/home.html
{% extends "base.html" %}

{% block content %}
    {% include "navigation.html" %}

    <div class="container content-inner">
      <div class="main-col">
          <section class="jumbo-card card">
              <div class="card-image">
                  <a href="{% url 'articles:article' main_article.url_headline %}"><img src="{{ main_article.image_url }}" alt="" class="img-responsive"></a>
              </div>
              <div class="card-elements">
                  <div class="card-header">
                      <a href="{% url 'articles:article' main_article.url_headline %}"><h3>{{ main_article.headline }}</h3></a>
                      <p class="author">{{ main_article.author }} | {{ main_article.publish_date }}</p>
                  </div>
                  <div class="card-copy">
                      <p>{{ main_article.promo }}</p>
                  </div>
              </div>
          </section>
      </div>
      <div class="cards row">
          {% for article in other_articles %}
          <div class="card">
              <div class="card-image">
                  <a href="{% url 'articles:article' article.url_headline %}">
                      <img src="{{ article.image_url }}" alt="">
                  </a>
              </div>
              <div class="card-elements">
                  <div class="card-header">
                      <a href="{% url 'articles:article' article.url_headline %}">
                          <h4>{{ article.headline }}</h4>
                      </a>
                      <p class="author">{{ article.author }} | {{ article.publish_date }}</p>
                  </div>
                  <div class="card-copy">
                      <p>{{ article.promo }}</p>
                  </div>
              </div>
          </div>
          {% endfor %}
      </div> 
  </div>
{% endblock %}

articles/templates/navigation.html
<div class="container top-bar">
  <a href="/" class="btn btn-primary">HOME</a>
</div>

articles/templates/quotes.html
<div class="block-title">
    <hr><h2>Stocks</h2>
</div>
<ul id="quote-list" class="list-unstyled">
{% for quote in quotes %}
<li class="ticker-row">
    <div>
        <h3>{{ quote.CompanyName}}</h3>
        <h4>
            <span class="ticker">
                <a title="{{ quote.CompanyName }} Stock Quote" href="#">
                    {{ quote.Exchange }}:<span class="symbol">{{ quote.Symbol}}</span>
                </a>
            </span>
        </h4>
        <aside class="price-quote-container">
            <h4 class="current-price">
                ${{ quote.CurrentPrice.Amount }}
            </h4>
            <h4 class="price-change-amount {% if quote.Change.Amount > 0 %} price-pos {% elif quote.Change.Amount < 0 %} price-neg {% endif %}">
                ${{ quote.Change.Amount }}
            </h4>
            <h4 class="price-change-percent {% if quote.Change.Amount > 0 %} price-pos {% elif quote.Change.Amount < 0 %} price-neg {% endif %}">
                ({{ quote.change_percent }}%)
            </h4>
        </aside>
    </div>
</li>
{% endfor %}
</ul>
<button id="shuffle" type="button" onclick="shuffleList('quote-list');">Shuffle quotes</button>